export const LISTAR_USERS = 'LISTAR_USERS'
export const CADASTRAR_USER = 'CADASTRAR_USER'
export const EDITAR_USER = 'EDITAR_USER'
export const EXCLUIR_USER = 'EXCLUIR_USER'
export const GET_USER = 'GET_USER'

export const SALVAR_AUTH = 'SALVAR_AUTH'

export const ADD_AUTH_USER_FIREBASE = 'ADD_AUTH_USER_FIREBASE'
export const GET_TOKEN = 'GET_TOKEN'