export const LISTAR_USERS = 'LISTAR_EVENTOS'
export const CADASTRAR_USER = 'CADASTRAR_EVENTO'
export const EDITAR_USER = 'EDITAR_EVENTO'
export const EXCLUIR_USER = 'EXCLUIR_EVENTO'

export const SALVAR_AUTH = 'SALVAR_AUTH'

export const ADD_AUTH_USER_FIREBASE = 'ADD_AUTH_USER_FIREBASE'